<a href="https://colab.research.google.com/github/papillonbee/logistic_regression/blob/master/Logistic_Regression_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression from Scratch with Gradient Descent and Newton's Method

Author: Papan Yongmalwong

## Introduction to Logistic Regression

### From Statistics Point of View

Given explanatory matrix $\textbf{X}$ of size $n\times p$ and response vector $\textbf{Y}$ of size $n\times1$

where element $x_{ij}\in\textbf{X}$ takes any real value and element $y_i\in\textbf{Y}$ takes only binary value ($0$, $1$)

$\textbf{X}$ | | | |$\textbf{Y}$
--- | --- | --- | --- | --- 
$x_{1,1}$ | $x_{1,2}$ | $\cdots$ | $x_{1,p}$ | $y_1$
$x_{2,1}$ | $x_{2,2}$ | $\cdots$ | $x_{2,p}$ | $y_2$
$\vdots$ | $\vdots$ | $\ddots$ | $\vdots$ | $\vdots$
$x_{n,1}$ | $x_{n,2}$ | $\cdots$ | $x_{n,p}$ | $y_n$

The goal is to find a model that is able to predict the probability of $y^*=1$ given new explanatory variable $\textbf{x}^*=\begin{bmatrix}x_1*&x_2*&...&x_p*\end{bmatrix}^T$.

The model that is suitable for this problem is the logit model where we treat each response variable $Y_i$, conditioned on explanatory variable $\textbf{x}_i=\begin{bmatrix}x_{i1}&x_{i1}&\cdots&x_{ip}\end{bmatrix}^T$ as a random variable such that $Y_i|\textbf{x}_i\sim Bernoulli(p_i)$ where $p_i=Pr(Y_i=1|\textbf{x}_i)=\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}$ and that $Y_i|\textbf{x}_i's$ are independent, for every row $i=1,...,n$.

It is noteworthy that $Y_i|\textbf{x}_i's$ are random variables, $\textbf{x}_i's$ are constant $p\times1$ vectors and $y_i's$ are constant binary values ($0$, $1$) and $\boldsymbol{\beta}$ is an unknown $p\times1$ vector.

The goal then becomes solving for coefficients $\boldsymbol{\beta}$ that satisfies the logit model assumption on $\textbf{X}$ and $\textbf{Y}$.

Solving for $\boldsymbol{\beta}$ can be done by maximum likelihood estimation.

$\hat{\boldsymbol{\beta}}=argmax_{\boldsymbol{\beta}}\mathcal{L}(\boldsymbol{\beta})$

$\mathcal{L}(\boldsymbol{\beta})$ $=Pr(Y_1=y_1,Y_2=y_2,...,Y_n=y_n|\textbf{X})\\
=\prod_{i=1}^nPr(Y_i=y_i|\textbf{x}_i)\\
=\prod_{i=1}^np_i^{y_i}(1-p_i)^{1-y_i}\\
=\prod_{i=1}^n(\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}})^{y_i}(\frac{1}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}})^{1-y_i}$

$\hat{\boldsymbol{\beta}}=argmin_{\boldsymbol{\beta}}-ln(\mathcal{L}(\boldsymbol{\beta}))$

$-ln(\mathcal{L}(\boldsymbol{\beta}))$ $=\sum_{i=1}^n[ln(1+e^{\textbf{x}_i^T\boldsymbol{\beta}})-y_i\textbf{x}_i^T\boldsymbol{\beta}]$

Here, $\hat{\boldsymbol{\beta}}$ is a maximum likelihood estimator for $\boldsymbol{\beta}$.

There is no closed form for finding $\hat{\boldsymbol{\beta}}$, thus iterative method is required.

This [colab](https://colab.research.google.com/drive/1BxzwemHWPXJOFXoI7JBONQEohTjt7Msd) will guide you to finding $\hat{\boldsymbol{\beta}}$ with $2$ iterative methods, which are **Gradient Descent** and **Newton's Method**.

### From Operations Research Point of View

The logistic regression model can be viewed as a convex program. Solving for $\boldsymbol{\beta}$ by maximum likelihood estimation can be viewed as solving for optimal solution in a convex program.

Let $f(\boldsymbol{\beta})=-ln(\mathcal{L}(\boldsymbol{\beta}))$

Decision variables: $\boldsymbol{\beta}\in\mathbb{R}^p$

Convex program: $min\ f(\boldsymbol{\beta})\\
s.t. \boldsymbol{\beta}\in\mathbb{R}^p$

It can be proven that the objective function $f(\boldsymbol{\beta})$ is a convex function, which is a requirement for a program to be convex.

Both **Gradient Descent** and **Newton's Method** guarantee an optimal solution for $\boldsymbol{\beta}$ in a convex program.

**Proof:** $f(\boldsymbol{\beta})=-ln(\mathcal{L}(\boldsymbol{\beta}))$ is a convex function

**Please feel free to skip the proof if you are not into mathematics*

The proof requires a theorem which states that for a twice differentiable function $f:\mathbb{R}^p\rightarrow\mathbb{R}$, $f(\textbf{x})$ is a convex function if and only if $\nabla^2f(\textbf{x})$ is positive semi-definite

From $f(\boldsymbol{\beta})=-ln(\mathcal{L}(\boldsymbol{\beta}))=\sum_{i=1}^n[ln(1+e^{\textbf{x}_i^T\boldsymbol{\beta}})-y_i\textbf{x}_i^T\boldsymbol{\beta}]$

$\nabla f(\boldsymbol{\beta})=\sum_{i=1}^n(\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}-y_i)\textbf{x}_i$

$\nabla^2f(\boldsymbol{\beta})=\sum_{i=1}^n\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}\frac{1}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}\textbf{x}_i\textbf{x}_i^T$

Consider $\textbf{A}_i=\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}\frac{1}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}\textbf{x}_i\textbf{x}_i^T$

For non-zero vector $\textbf{u}\in\mathbb{R}^p$, $\textbf{u}^T\textbf{A}_i\textbf{u}$ $=\textbf{u}^T(\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}\frac{1}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}\textbf{x}_i\textbf{x}_i^T)\textbf{u}\\
=\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}\frac{1}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}(\textbf{x}_i^T\textbf{u})^T(\textbf{x}_i^T\textbf{u})\geq0$

Thus, $\textbf{A}_i$ is positive semi-definite. Moreover, the sum of positive semi-definite matrices is still a positive semi-definite matrix.

Therefore, $\nabla^2f(\boldsymbol{\beta})$ is positive semi-definite. As a result, $f(\boldsymbol{\beta})$ is a convex function.

### From Neural Network Point of View

The logistic regression model can also be viewed as a neural network model with $1$ input layer and $1$ output layer (no hidden layer). Suppose there is explanatory matrix $\textbf{X}$ of size $n\times p$ and response vector $\textbf{Y}$ of size $n\times 1$. The input layer will consist of $k$ nodes (the number of columns in $\textbf{X}$) and the output layer will consist of $1$ node (the number of columns in $\textbf{Y}$). The activation function for the node in the output layer is the sigmoid function and the loss function for the model is the negative log-likelihood $f(\boldsymbol{\beta})=-ln(\mathcal{L}(\boldsymbol{\beta}))$ (or binary cross-entropy). Solving for $\boldsymbol{\beta}$ by maximum likelihood estimation can be viewed as training this neural network with input $\textbf{X}$ and output $\textbf{Y}$, which produces the coefficients $\boldsymbol{\beta}$.

Suppose you have $p=10$, the neural network architecture for logistic regression model will be as follows:

<img src='https://raw.githubusercontent.com/papillonbee/images/master/nn_logistic.png' alt="Drawing" style="width: 200px;"/>

## Gradient Descent

[Gradient descent](https://en.wikipedia.org/wiki/Gradient_descent)  is an iterative method that solves for minimum of a convex function.

For a convex function $f(\textbf{x})$, the step taken in each iteration is proportional to the steepest descent direction of $f(\textbf{x})$, which is $-\frac{\nabla f(\textbf{x})}{\|\nabla f(\textbf{x})\|}$. Please see **Appendix** for further detail on the intuition of gradient descent.

$\textbf{x}\leftarrow\textbf{x}-\lambda\nabla f(\textbf{x})$

$\lambda$ is the step size in each iteration

$\nabla f(\textbf{x})$ is the gradient of $f(\textbf{x})$

The method stops when  $f(\textbf{x})$ is close to the minimum, or $\nabla f(\textbf{x})$ is close to $\textbf{0}$.

The gradient descent algorithm that solves for $\boldsymbol{\beta}$ in logistic regression will be as follows:

`while` $\|\nabla f(\boldsymbol{\beta})\|$ `>` $\epsilon$`:`

$\ \ \ \ \boldsymbol{\beta}\leftarrow\boldsymbol{\beta}-\lambda\nabla f(\boldsymbol{\beta})$

$\lambda$ is the parameter you have to specify. It is recommended to take a small step; i.e. $\lambda=0.001$ is used as an example below. Too small step size may result in a slow rate of convergence while too large step size may result in a divergence.

Note that $\lambda$ is not required to be fixed at every iteration. Instead, $\lambda$ is allowed to change at every iteration and is chosen via [line search](https://en.wikipedia.org/wiki/Line_search). Here, $\lambda$ is chosen to be fixed just for simplicity.

The chosen stopping criterion here is the Euclidean norm of $\nabla f(\boldsymbol{\beta})$ not exceeding a pre-specified tolerance $\epsilon$.

## Newton's Method

[Newton's method](https://en.wikipedia.org/wiki/Newton%27s_method_in_optimization) is an iterative method that solves for minimum of a convex function. Equivalently, the method solves for root of the derivative of the convex function. The idea behind this method is to use a quadratic approximate of the convex function and solve for its minimum at each step. Please see **Appendix** for further detail on the intuition of Newton's method.

For a convex function $f(\textbf{x})$, the step taken in each iteration is $-(\nabla^2f(\textbf{x}))^{-1}\nabla f(\textbf{x})$.

$\textbf{x}\leftarrow\textbf{x}-(\nabla^2f(\textbf{x}))^{-1}\nabla f(\textbf{x})$

$\nabla f(\textbf{x})$ is the gradient of $f(\textbf{x})$

$\nabla^2f(\textbf{x})$ is the Hessian matrix of $f(\textbf{x})$

The method stops when  $f(\textbf{x})$ is close to the minimum, or $\nabla f(\textbf{x})$ is close to $\textbf{0}$.

The Newton's method algorithm that solves for $\boldsymbol{\beta}$ in logistic regression will be as follows:

`while` $\|\nabla f(\boldsymbol{\beta})\|$ `>` $\epsilon$`:`

$\ \ \ \ \boldsymbol{\beta}\leftarrow\boldsymbol{\beta}-(\nabla^2f(\boldsymbol{\beta}))^{-1}\nabla f(\boldsymbol{\beta})$

The chosen stopping criterion here is the Euclidean norm of $\nabla f(\boldsymbol{\beta})$ not exceeding a pre-specified tolerance $\epsilon$.

## Implementation of Logistic Regression from Scratch

### Generate Dataset $\textbf{X}$ and $\textbf{Y}$

*   $\textbf{X}$ is a matrix of size $2,\!484\times 2$
*   $\textbf{Y}$ is a vector of size $2,\!484\times 1$


In [0]:
import numpy as np

X = np.matrix(np.ones(2484)).T
X = np.append(X,np.matrix([0]*1379+[2]*638+[4]*213+[5]*254).T,axis=1)
Y = np.matrix([1]*24+[0]*1355+[1]*35+[0]*603+[1]*21+[0]*192+[1]*30+[0]*224).T
print(X)
print(Y)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 5.]
 [1. 5.]
 [1. 5.]]
[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


### Define $f(\boldsymbol{\beta})$, $\nabla f(\boldsymbol{\beta})$, and $\nabla^2f(\boldsymbol{\beta})$

Please see **Appendix** for compact notation of $f(\boldsymbol{\beta})$, $\nabla f(\boldsymbol{\beta})$, and $\nabla^2f(\boldsymbol{\beta})$

In [0]:
def f(beta):
  return np.ravel(np.ones(len(Y))*(np.log(1+np.exp(X*beta)))-Y.T*X*beta)[0]

def nabla_f(beta):
  return X.T*(1/(1+1/np.exp(X*beta))-Y)

def nabla2_f(beta):
  return X.T*(np.diag(np.exp(X*beta)/np.power(1+np.exp(X*beta),2))*X)

### Implement Gradient Descent Algorithm ($\lambda=0.001$)

The algorithm converges to $\|\nabla f(\boldsymbol{\beta})\|\leq10^{-10}$ at $771$ iterations

$\boldsymbol{\beta}=\begin{bmatrix}-3.8662481&0.39733662\end{bmatrix}^T$

In [0]:
beta = np.matrix(np.zeros(X.shape[1])).T
TOL = np.power(10.,-10)
lam = 0.001
counter = 0
while np.linalg.norm(nabla_f(beta)) > TOL:
  counter += 1
  beta = beta-lam*nabla_f(beta)
  print('iter =',counter)
  print(beta)
  print('norm =',np.linalg.norm(nabla_f(beta)))

iter = 1
[[-1.132]
 [-1.395]]
norm = 366.4091082138964
iter = 2
[[-1.37091275]
 [-1.11719371]]
norm = 325.5812674774396
iter = 3
[[-1.55786334]
 [-0.8506367 ]]
norm = 292.04949741159606
iter = 4
[[-1.71359216]
 [-0.60357104]]
norm = 255.1846133480213
iter = 5
[[-1.85238691]
 [-0.38943275]]
norm = 210.07434508461156
iter = 6
[[-1.98458591]
 [-0.22617022]]
norm = 165.54273460705838
iter = 7
[[-2.11451764]
 [-0.12359273]]
norm = 136.5581751475123
iter = 8
[[-2.23810505]
 [-0.06550412]]
norm = 118.57149977392974
iter = 9
[[-2.34988745]
 [-0.025958  ]]
norm = 104.69787504328973
iter = 10
[[-2.44943555]
 [ 0.00647381]]
norm = 93.36089278350121
iter = 11
[[-2.53848886]
 [ 0.03450528]]
norm = 83.92749976825525
iter = 12
[[-2.61871984]
 [ 0.0591389 ]]
norm = 75.96590171504594
iter = 13
[[-2.69146447]
 [ 0.08102581]]
norm = 69.16413293946216
iter = 14
[[-2.75778764]
 [ 0.10064505]]
norm = 63.29152492986966
iter = 15
[[-2.8185491 ]
 [ 0.11836121]]
norm = 58.17414856400428
iter = 16
[[-2.87445177]

### Implement Newton's Method Algorithm

The algorithm converges to $\|\nabla f(\boldsymbol{\beta})\|\leq10^{-10}$ at $7$ iterations

$\boldsymbol{\beta}=\begin{bmatrix}-3.8662481&0.39733662\end{bmatrix}^T$

In [0]:
beta = np.matrix(np.zeros(X.shape[1])).T
TOL = np.power(10.,-10)
counter = 0
while np.linalg.norm(nabla_f(beta)) > TOL:
  counter += 1
  beta -= np.linalg.inv(nabla2_f(beta))*nabla_f(beta).T
  print('iter =',counter)
  print(beta)
  print('norm =',np.linalg.norm(nabla_f(beta)))

iter = 1
[[-1.93251069]
 [ 0.08015202]]
norm = 344.0674429365813
iter = 2
[[-2.91445219]
 [ 0.19953576]]
norm = 78.8473161236118
iter = 3
[[-3.56822777]
 [ 0.32983402]]
norm = 14.865386138822815
iter = 4
[[-3.83189761]
 [ 0.38960211]]
norm = 1.5569804528923392
iter = 5
[[-3.86575804]
 [ 0.39722704]]
norm = 0.0224489498794286
iter = 6
[[-3.866248 ]
 [ 0.3973366]]
norm = 4.632921725232224e-06
iter = 7
[[-3.8662481 ]
 [ 0.39733662]]
norm = 5.444006648261367e-13


### Check Coefficients from `sklearn.linear_model.LogisticRegression`

$\boldsymbol{\beta}=\begin{bmatrix}-3.86624885&0.39733451\end{bmatrix}^T$

In [0]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(solver='lbfgs',C=1e9,fit_intercept=False).fit(X,np.ravel(Y))
np.set_printoptions(suppress=True)
print(clf.coef_)

[[-3.86624885  0.39733451]]


## Conclusion

In comparing the efficiency of Newton's method and gradient descent for solving the coefficients $\boldsymbol{\beta}\in\mathbb{R}^{p}$ in logistic regression model given explanatory matrix $\textbf{X}\in\mathbb{R}^{n\times p}$ and response vector $\textbf{Y}\in\mathbb{R}^{n}$, the runtime complexity for each iteration in Newton's method is $\mathcal{O}(np(n+p)+p^3)$ while the runtime complexity for each iteration in gradient descent is $\mathcal{O}(np)$. The memory complexity for each iteration in Newton's method is $\mathcal{O}(p^2)$ while the memory complexity for each iteration in gradient descent is $\mathcal{O}(p)$. It can be seen that Newton's method requires more number of operations and more amount of memory than gradient descent at each iteration. However, Newton's method requires less iterations to converge to minimum because it uses the knowledge of the second derivative $\nabla^2f(\boldsymbol{\beta})$ at each iteration while gradient descent only uses the knowledge of the first derivative $\nabla f(\boldsymbol{\beta})$ at each iteration. This is the trade-off between the complexity and speed of convergence of Newton's method and gradient descent. In fact, the Newton's method is very fast to converge yet requires high amount of complexity for computing the inverse of Hessian matrix $\nabla^2f(\boldsymbol{\beta})$.  Computing the inverse of Hessian matrix can be unavailable for a very large dataset. In real world, ones ought to approximate the inverse of Hessian matrix, leading to less complexity, in exchange for more iterations to converge to minimum. The methods are called [the Quasi-Newton methods](https://en.wikipedia.org/wiki/Quasi-Newton_method). It is noteworthy that the solver specified in `sklearn.linear_model.LogisticRegression` is `solver='lbfgs'` or [Limited-memory BFGS](https://en.wikipedia.org/wiki/Limited-memory_BFGS), an iterative method in the family of Quasi-Newton methods.

## Appendix

### Intuition of Gradient Descent

Gradient descent is an iterative method that solves for minimum of a convex function. The method moves the guessing point to the next guessing point in the direction that $f(\textbf{x})$ decreases the fastest.

To move in the direction that $f(\textbf{x})$ decreases the fastest, consider the theorem

>For $f(\textbf{x})\in\mathbb{R}$, a unit vector $-\frac{\nabla f(\textbf{x}_0)}{\|f(\textbf{x}_0)\|}$ is the steepest descent direction of $f(\textbf{x})$ at $\textbf{x}=\textbf{x}_0$

In gradient descent, in order to find the minimum of the convex function $f(\textbf{x})$, we start from our initial guess $\textbf{x}_0$,  move $\textbf{x}_0$ to the next point in the direction that $f(\textbf{x})$ decreases the fastest $\textbf{x}_0-\lambda_0\nabla f(\textbf{x}_0)$, let $\textbf{x}_1=\textbf{x}_0-\lambda_0\nabla f(\textbf{x}_0)$ be the next guess, move $\textbf{x}_1$ to the next point in the direction that $f(\textbf{x})$ decreases the fastest $\textbf{x}_1-\lambda_1\nabla f(\textbf{x}_1)$, let $\textbf{x}_2=\textbf{x}_1-\lambda_1\nabla f(\textbf{x}_1)$ be the next guess, and do these steps recursively until $f(\textbf{x}_i)$ is close to minimum. Therefore, gradient descent algorithm can be written in a recursive form as follows:

$\textbf{x}_{i+1}\leftarrow\textbf{x}_i-\lambda_i\nabla f(\textbf{x}_i)$ for arbitrary value of $\lambda_i$

At each iteration, $\lambda_i$ is chosen such that $f(\textbf{x}_i-\lambda_i\nabla f(\textbf{x}_i))$ is smallest. This can be done via [line search](https://en.wikipedia.org/wiki/Line_search).

You can see that gradient descent moves from point $\textbf{x}_i$ to point $\textbf{x}_{i+1}$ in the direction $-\lambda_i\nabla f(\textbf{x}_i)$, which is proportional to $-\frac{\nabla f(\textbf{x}_i)}{\|f(\textbf{x}_i)\|}$, the steepest descent direction of $f(\textbf{x})$ at $\textbf{x}=\textbf{x}_i$.

### Intuition of Newton's Method

Newton's method is an iterative method that solves for minimum of a convex function. The method uses the quadratic approximate of the convex function and solves for its minimum at each step.

To approximate the convex function with quadratic function at each step, consider Taylor series of $f(\textbf{x})$ centered at $\textbf{x}=\textbf{x}_0$

$f(\textbf{x})=f(\textbf{x}_0)+(\textbf{x}-\textbf{x}_0)^T\nabla f(\textbf{x}_0)+\frac{1}{2}(\textbf{x}-\textbf{x}_0)^T\nabla^2f(\textbf{x}_0)(\textbf{x}-\textbf{x}_0)+...$

Approximate $f(\textbf{x})$ to polynomial of degree $2$

$f(\textbf{x})\approx f(\textbf{x}_0)+(\textbf{x}-\textbf{x}_0)^T\nabla f(\textbf{x}_0)+\frac{1}{2}(\textbf{x}-\textbf{x}_0)^T\nabla^2f(\textbf{x}_0)(\textbf{x}-\textbf{x}_0)$

Take gradient on both sides

$\nabla f(\textbf{x})\approx\nabla f(\textbf{x}_0)+\frac{1}{2}(\nabla^2f(\textbf{x}_0)+\nabla^2f(\textbf{x}_0)^T)(\textbf{x}-\textbf{x}_0)$

$\nabla f(\textbf{x})\approx\nabla f(\textbf{x}_0)+\nabla^2f(\textbf{x}_0)(\textbf{x}-\textbf{x}_0)$

Let $\nabla f(\textbf{x})=0$ and solve for $\textbf{x}$

$\nabla f(\textbf{x})=0\approx\nabla f(\textbf{x}_0)+\nabla^2f(\textbf{x}_0)(\textbf{x}-\textbf{x}_0)$

$\textbf{x}\approx\textbf{x}_0-(\nabla^2f(\textbf{x}_0))^{-1}\nabla f(\textbf{x}_0)$

Here, $\textbf{x}$ is the minimum from the quadratic approximate of $f(\textbf{x})$ centered at $\textbf{x}=\textbf{x}_0$.

In Newton's method, we let $\textbf{x}_1=\textbf{x}$ be the next point for Taylor series to be centered at, we then find the minimum from the quadratic approximate of $f(\textbf{x})$ centered at $\textbf{x}=\textbf{x}_1$ and obtain the minimum $\textbf{x}$, set $\textbf{x}_2=\textbf{x}$ and do these steps recursively until $f(\textbf{x}_i)$ is close to minimum. Therefore, Newton's method algorithm can be written in a recursive form as follows:

$\textbf{x}_{i+1}\leftarrow\textbf{x}_i-(\nabla^2f(\textbf{x}_i))^{-1}\nabla f(\textbf{x}_i)$

### Compact Notation of $f(\boldsymbol{\beta})$, $\nabla f(\boldsymbol{\beta})$, and $\nabla^2f(\boldsymbol{\beta})$

The gradient and Hessian matrix of the negative log-likelihood  $f(\boldsymbol{\beta})=-ln(\mathcal{L}(\boldsymbol{\beta}))$ are derived as follows:

$f(\boldsymbol{\beta})$ $=-ln(\mathcal{L}(\boldsymbol{\beta}))\\=\sum_{i=1}^n[ln(1+e^{\textbf{x}_i^T\boldsymbol{\beta}})-y_i\textbf{x}_i^T\boldsymbol{\beta}]$

$\frac{\partial f(\boldsymbol{\beta})}{\partial\beta_j}$ $=\sum_{i=1}^n[\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}x_{ij}-y_ix_{ij}],\ \forall j=1,2,...,p$

$\therefore\nabla f(\boldsymbol{\beta})$ $=\sum_{i=1}^n(\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}-y_i)\textbf{x}_i$

$\frac{\partial^2 f(\boldsymbol{\beta})}{\partial\beta_j\partial\beta_k}$ $=\sum_{i=1}^n\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}\frac{1}{1+e^{\textbf{x}_i^T\boldsymbol{\beta}}}x_{ij}x_{ik},\ \forall j,k=1,2,...,p$

$\therefore\nabla^2f(\boldsymbol{\beta})$ $=\sum_{i=1}^n\frac{e^{\textbf{x}_i^T\boldsymbol{\beta}}}{(1+e^{\textbf{x}_i^T\boldsymbol{\beta}})^2}\textbf{x}_i\textbf{x}_i^T$


From above, $f(\boldsymbol{\beta})$, $\nabla f(\boldsymbol{\beta})$, and $\nabla^2f(\boldsymbol{\beta})$ can be written in a more compact form as follows:

$f(\boldsymbol{\beta})=\textbf{1}^Tln(1+e^{\textbf{X}\boldsymbol{\beta}})-\textbf{Y}^T\textbf{X}\boldsymbol{\beta}$

$\nabla f(\boldsymbol{\beta})=\textbf{X}^T(\frac{e^{\textbf{X}\boldsymbol{\beta}}}{1+e^{\textbf{X}\boldsymbol{\beta}}}-\textbf{Y})$

$\nabla^2f(\boldsymbol{\beta})=\textbf{X}^Tdiag(\frac{e^{\textbf{X}\boldsymbol{\beta}}}{1+e^{\textbf{X}\boldsymbol{\beta}}}\circ\frac{1}{1+e^{\textbf{X}\boldsymbol{\beta}}})\textbf{X}$

Here, $\textbf{X}\in\mathbb{R}^{n\times p}\\
\textbf{Y}\in\mathbb{R}^n\\
\boldsymbol{\beta}\in\mathbb{R}^p\\
\textbf{1}\in\mathbb{R}^n\\
ln(1+e^{\textbf{X}\boldsymbol{\beta}})\in\mathbb{R}^n\\
\frac{e^{\textbf{X}\boldsymbol{\beta}}}{1+e^{\textbf{X}\boldsymbol{\beta}}}\in\mathbb{R}^n\\
\frac{1}{1+e^{\textbf{X}\boldsymbol{\beta}}}\in\mathbb{R}^n\\
diag(\frac{e^{\textbf{X}\boldsymbol{\beta}}}{1+e^{\textbf{X}\boldsymbol{\beta}}}\circ\frac{1}{1+e^{\textbf{X}\boldsymbol{\beta}}})\in\mathbb{R}^{n\times n}$

$diag()$ is a notation for diagonal matrix with entries specified inside the parenthesis

$\circ$ is a notation for a [Hadamard product](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)) (element-wise product)